language: go

go:
  - 1.x

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - npm install
  - elm-package install --yes

before_script:
 - npm run build

deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    on:
      tags: true
  - provider: heroku
    api_key: $HEROKU_AUTH_KEY
    app: golang-scaffolding
    on:
      all_branches: true
