language: go

go:
  - 1.x

jobs:
  include:
  - stage: deploy to production
    deploy:
      provider: heroku
      api_key: $HEROKU_AUTH_KEY
      app: golang-scaffolding
      on:
        all_branches: true
