language: go

go:
  - 1.x

env:
  - TRAVIS_NODE_VERSION="6.1.0"

install:
  - npm install

before_script:
 - npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_KEY
  app: golang-scaffolding
  on:
    all_branches: true
