language: go

go:
  - 1.x

node_js:
  - 6.1.x

install:
  - npm install

before_script:
 - npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_KEY
  app: golang-scaffolding
  on:
    all_branches: true
