language: go

go:
  - 1.x

env:
  - TRAVIS_NODE_VERSION="6.1.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
 - npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_KEY
  app: golang-scaffolding
  on:
    all_branches: true
