language: go

go:
  - 1.x

env:
  - TRAVIS_NODE_VERSION="6.1.0"

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
 - npm run build

deploy:
  - provider: releases
    user: $GITHUB_USERNAME
    password: $GITHUB_PASSWORD
    file_glob: true
    file: ./*
    skip_cleanup: true
    on:
      tags: true
  - provider: heroku
    api_key: $HEROKU_AUTH_KEY
    app: golang-scaffolding
    on:
      all_branches: true
