language: go

go:
  - 1.x

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

deploy:
  - provider: heroku
    api_key: $HEROKU_AUTH_KEY
    app: trips
    skip_cleanup: true
    on:
      all_branches: true
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    on:
      tags: true
