language: go

go:
  - 1.x

go_import_path: github.com/oskarszura/src

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

deploy:
  - provider: heroku
    api_key: $HEROKU_AUTH_KEY
    app: golang-scaffolding
    skip_cleanup: true
    overwrite: true
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    on:
      tags: true
